plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.146'
}

def mod_id = "primogemcraft"

version = mod_version

repositories {
    mavenLocal()
    maven { url = 'https://maven.theillusivec4.top/' }
    maven { url = 'https://maven.shedaniel.me/' }
    exclusiveContent {
        forRepository {
            maven { url = 'https://api.modrinth.com/maven' }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    exclusiveContent {
        forRepository {
            maven { url = 'https://cursemaven.com' }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }


dependencies {
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
    compileOnly "maven.modrinth:genshincraft:3.1.3"
    implementation "maven.modrinth:elixir_dan:1.3.4"
    api "me.shedaniel:RoughlyEnoughItems-neoforge:16.0.799"
    api "me.shedaniel.cloth:cloth-config-neoforge:15.0.140"
    implementation "maven.modrinth:jade:15.10.5+neoforge"
    implementation "maven.modrinth:tacz-1.21.1:1.1.8-hotfix-r6"
    implementation "maven.modrinth:farmers-delight:1.21.1-1.3.4"
    implementation "maven.modrinth:teyvats-delight:0.2.31"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [neo_version: neo_version,
                             mod_version: mod_version,
                             mod_id     : mod_id]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
